# Generated by Django 4.0.6 on 2022-07-23 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('developer', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('professional', models.BooleanField()),
                ('image', models.ImageField(height_field=650, upload_to='static/main/assets/img/portfolio', width_field=900)),
                ('url', models.URLField(max_length=400)),
            ],
        ),
    ]
