# Generated by Django 4.0.6 on 2022-07-24 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_image_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='name',
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, upload_to='myportfolio\\main\\static\\main\x07ssets\\img\\portfolio'),
        ),
    ]
