# Generated by Django 4.0.6 on 2022-07-24 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='myportfolio/main/static/main/assets/img'),
        ),
        migrations.AlterField(
            model_name='project',
            name='developer',
            field=models.CharField(default='Abyan Majid', max_length=250),
        ),
    ]
