# Generated by Django 4.0.6 on 2022-07-25 04:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_project_category_project_release_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Changelog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=15)),
                ('changes', models.CharField(max_length=250)),
                ('release_date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
