# Generated by Django 4.0.6 on 2022-07-25 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_changelog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Changelog',
        ),
    ]
