# Generated by Django 4.0.6 on 2022-07-25 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_changes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Changes',
            new_name='Change',
        ),
    ]
