# Generated by Django 4.0.6 on 2022-07-25 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_rename_changes_change'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation', models.CharField(max_length=30)),
                ('about_me', models.CharField(max_length=300)),
                ('featured_work1_title', models.CharField(max_length=100)),
                ('featured_work2_title', models.CharField(max_length=100)),
                ('featured_work3_title', models.CharField(max_length=100)),
                ('featured_work4_title', models.CharField(max_length=100)),
                ('featured_work5_title', models.CharField(max_length=100)),
                ('featured_work6_title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=200)),
                ('education', models.CharField(max_length=200)),
                ('homepagedetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.homepagedetails')),
            ],
        ),
    ]
