# Generated by Django 4.0.6 on 2022-07-25 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_homepagedetails_education'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomePageDetails',
            new_name='HomePage',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='homepagedetails',
            new_name='homepage',
        ),
    ]
