# Generated by Django 4.0.6 on 2022-07-25 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_rename_homepagedetails_homepage_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='HomePage',
        ),
    ]
