# Generated by Django 4.0.6 on 2022-07-25 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_homepage_education'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='HomePage',
        ),
    ]
