# Generated by Django 4.0.6 on 2022-07-25 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_featuredwork_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
