# Generated by Django 4.0.6 on 2022-07-25 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_project_featured_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='featured_image',
            new_name='featured_image_650x650',
        ),
    ]
