# Generated by Django 4.0.6 on 2022-07-25 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_rename_featured_image_project_featured_image_650x650'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Education',
        ),
    ]
