# Generated by Django 4.0.6 on 2022-07-25 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_delete_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=200)),
                ('featuredwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.featuredwork')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=200)),
                ('education', models.CharField(max_length=200)),
                ('featuredwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.featuredwork')),
            ],
        ),
    ]
